# Prometheus on OpenShift

This repository contains definitions and tools to run Prometheus and its associated ecosystem on Red Hat OpenShift.

## Components

The following components are available:

* link:https://prometheus.io/docs/introduction/overview/[Prometheus]
* link:https://prometheus.io/docs/instrumenting/exporters/[node-exporter]
* link:https://prometheus.io/docs/alerting/alertmanager/[Alertmanager]

## Project Organization

A new project called _prometheus_ will be created to contain the entire ecosystem

Execute the following command to create the project:

[source,bash]
----
oc new-project prometheus --display-name="Prometheus"
----

## Deploy Prometheus

An OpenShift template has been provided to streamline the deployment to OpenShift.

Because of a bug in the current Prometheus 2.0.0 alpha 2 image there is no persistent volume available at the moment. This will be updated once Prometheus 2.0 ships.

Execute the following command to add the template to the project and instantiate the template:

[source,bash]
----
oc create -f prometheus_3.5.yaml
oc new-app --template=prometheus
----

## Next Steps

Please refer to the following to enhance the functionality of Prometheus

* link:Alertmanager[alertmanager]
* link:node-exporter[node-exporter]
* link:https://github.com/wkulhanek/docker-openshift-grafana[Grafana]
