# Prometheus on OpenShift

This repository contains definitions and tools to run Prometheus and its associated ecosystem on Red Hat OpenShift.

## Components

The following components are available:

* link:https://prometheus.io/docs/introduction/overview/[Prometheus]
* link:https://prometheus.io/docs/instrumenting/exporters/[node-exporter]
* link:https://prometheus.io/docs/alerting/alertmanager/[Alertmanager]

## Project Organization

A new project called _prometheus_ will be created to contain the entire ecosystem.

Execute the following command to create the project:

[source,bash]
----
oc new-project prometheus --display-name="Prometheus Monitoring"
----

## Deploy Prometheus

An OpenShift template has been provided to streamline the deployment to OpenShift.

Execute the following command to instantiate the Prometheus template:

[source,bash]
----
oc new-app -f prometheus.yaml
----

## Next Steps

Please refer to the following to enhance the functionality of Prometheus

* link:alertmanager[Alertmanager]
* link:node-exporter[Node exporter]
* link:https://github.com/wkulhanek/docker-openshift-grafana[Grafana]

# Cleanup

Simply delete the project and the cluster-reader binding (which gets created by the template but doesn't get deleted as part of the project):

[source,bash]
----
oc delete project prometheus
oc delete clusterrolebinding prometheus-cluster-reader
----
