# OpenShift Prometheus Node Exporter

The Node Exporter provides OS and system level metrics for Prometheus. The exporter runs as a link:https://docs.openshift.com/container-platform/latest/dev_guide/daemonsets.html[DaemonSet] to guarantee each node runs at least one copy of the application.

## Deployment to OpenShift

To deploy the node-exporter to OpenShift, complete the following steps.

### Open Firewall Ports

Port 9100 needs to be opened on each OpenShift host in order for the Prometheus server to scrape the metrics. Execute the following command to allow traffic to this port.

[source,bash]
----
iptables -A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 9100 -j ACCEPT
iptables-save
----

### Elevated Access

Since the node exporter will be accessing resources from each host, the service account being used to run the pod must be granted elevated access. Execute the following command to add the _default_ Service Account in the _prometheus_ project to the _privileged_ SCC>

[source,bash]
----
oc adm policy add-scc-to-user privileged system:serviceaccount:prometheus:default
----

### Instantiate the Template

Execute the following command to add and instantiate the node-exporter template

[source,bash]
----
oc create -f node-exporter-template.yaml
oc new-app --template=node-exporter
----

