# OpenShift Prometheus Node Exporter

The Node Exporter provides OS and system level metrics for Prometheus. The exporter runs as a link:https://docs.openshift.com/container-platform/latest/dev_guide/daemonsets.html[DaemonSet] to guarantee each node runs at least one copy of the application.

## Deployment to OpenShift

To deploy the node-exporter to OpenShift, complete the following steps.

### Open Firewall Ports

Port 9100 needs to be opened on each OpenShift host in order for the Prometheus server to scrape the metrics.

Add the following line to `/etc/sysconfig/iptables`:

[source,bash]
----
-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 9100 -j ACCEPT
----

Restart _iptables_ and OpenShift services in order to properly rebuild the rules

NOTE: The following commands will cause all running containers on the node to stop and restart

[source,bash]
----
systemctl reload  iptables
systemctl restart iptables.service
systemctl restart docker
systemctl restart atomic-openshift-node.service
----

### Elevated Access

Since the node exporter will be accessing resources from each host, the service account being used to run the pod must be granted elevated access. Execute the following command to add the _default_ Service Account in the _prometheus_ project to the _privileged_ SCC:

[source,bash]
----
oc adm policy add-scc-to-user privileged system:serviceaccount:prometheus:default
----

### Instantiate the Template

Execute the following command to add and instantiate the node-exporter template

[source,bash]
----
oc create -f node-exporter-template.yaml
oc new-app --template=node-exporter
----
